FROM python:3.8-slim

RUN apt-get update
RUN pip install --upgrade pip


COPY ./requirements.txt /home/app/
WORKDIR /home/app/
RUN pip install -r requirements.txt

COPY ./ /home/app
WORKDIR /home/app
CMD celery -A convert worker -l INFO -E --pool=solo --concurrency=1
